# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/chat.v1.ChatService/Chat',
                request_serializer=chat__pb2.ClientMessage.SerializeToString,
                response_deserializer=chat__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.CreateRoom = channel.unary_unary(
                '/chat.v1.ChatService/CreateRoom',
                request_serializer=chat__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=chat__pb2.CreateRoomResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/chat.v1.ChatService/GetConversation',
                request_serializer=chat__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=chat__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/chat.v1.ChatService/GetMessages',
                request_serializer=chat__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=chat__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/chat.v1.ChatService/SendMessage',
                request_serializer=chat__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SearchMessages = channel.unary_unary(
                '/chat.v1.ChatService/SearchMessages',
                request_serializer=chat__pb2.SearchMessagesRequest.SerializeToString,
                response_deserializer=chat__pb2.SearchMessagesResponse.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/chat.v1.ChatService/DeleteMessage',
                request_serializer=chat__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.DeleteMessageResponse.FromString,
                _registered_method=True)
        self.EditMessage = channel.unary_unary(
                '/chat.v1.ChatService/EditMessage',
                request_serializer=chat__pb2.EditMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.EditMessageResponse.FromString,
                _registered_method=True)
        self.MarkMessageRead = channel.unary_unary(
                '/chat.v1.ChatService/MarkMessageRead',
                request_serializer=chat__pb2.MarkMessageReadRequest.SerializeToString,
                response_deserializer=chat__pb2.MarkMessageReadResponse.FromString,
                _registered_method=True)
        self.GetUnreadCount = channel.unary_unary(
                '/chat.v1.ChatService/GetUnreadCount',
                request_serializer=chat__pb2.GetUnreadCountRequest.SerializeToString,
                response_deserializer=chat__pb2.GetUnreadCountResponse.FromString,
                _registered_method=True)
        self.RequestUpload = channel.unary_unary(
                '/chat.v1.ChatService/RequestUpload',
                request_serializer=chat__pb2.UploadRequest.SerializeToString,
                response_deserializer=chat__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetDownloadUrl = channel.unary_unary(
                '/chat.v1.ChatService/GetDownloadUrl',
                request_serializer=chat__pb2.GetDownloadUrlRequest.SerializeToString,
                response_deserializer=chat__pb2.GetDownloadUrlResponse.FromString,
                _registered_method=True)
        self.GetPresence = channel.unary_unary(
                '/chat.v1.ChatService/GetPresence',
                request_serializer=chat__pb2.GetPresenceRequest.SerializeToString,
                response_deserializer=chat__pb2.GetPresenceResponse.FromString,
                _registered_method=True)
        self.GetUserRooms = channel.unary_unary(
                '/chat.v1.ChatService/GetUserRooms',
                request_serializer=chat__pb2.GetUserRoomsRequest.SerializeToString,
                response_deserializer=chat__pb2.GetUserRoomsResponse.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/chat.v1.ChatService/CreateGroup',
                request_serializer=chat__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=chat__pb2.CreateGroupResponse.FromString,
                _registered_method=True)
        self.AddGroupMember = channel.unary_unary(
                '/chat.v1.ChatService/AddGroupMember',
                request_serializer=chat__pb2.AddGroupMemberRequest.SerializeToString,
                response_deserializer=chat__pb2.AddGroupMemberResponse.FromString,
                _registered_method=True)
        self.RemoveGroupMember = channel.unary_unary(
                '/chat.v1.ChatService/RemoveGroupMember',
                request_serializer=chat__pb2.RemoveGroupMemberRequest.SerializeToString,
                response_deserializer=chat__pb2.RemoveGroupMemberResponse.FromString,
                _registered_method=True)
        self.LeaveGroup = channel.unary_unary(
                '/chat.v1.ChatService/LeaveGroup',
                request_serializer=chat__pb2.LeaveGroupRequest.SerializeToString,
                response_deserializer=chat__pb2.LeaveGroupResponse.FromString,
                _registered_method=True)
        self.PromoteAdmin = channel.unary_unary(
                '/chat.v1.ChatService/PromoteAdmin',
                request_serializer=chat__pb2.PromoteAdminRequest.SerializeToString,
                response_deserializer=chat__pb2.PromoteAdminResponse.FromString,
                _registered_method=True)
        self.TransferOwnership = channel.unary_unary(
                '/chat.v1.ChatService/TransferOwnership',
                request_serializer=chat__pb2.TransferOwnershipRequest.SerializeToString,
                response_deserializer=chat__pb2.TransferOwnershipResponse.FromString,
                _registered_method=True)
        self.DeleteGroup = channel.unary_unary(
                '/chat.v1.ChatService/DeleteGroup',
                request_serializer=chat__pb2.DeleteGroupRequest.SerializeToString,
                response_deserializer=chat__pb2.DeleteGroupResponse.FromString,
                _registered_method=True)


class ChatServiceServicer:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def Chat(self, request_iterator, context):
        """Bidirectional streaming for live chat, typing indicators, read receipts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Create a DM or group room; DMs are idempotent for the same pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Get single conversation details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Load paginated message history for a room
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message via unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMessages(self, request, context):
        """Search messages within a conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Delete message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditMessage(self, request, context):
        """Edit message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkMessageRead(self, request, context):
        """Mark message as read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnreadCount(self, request, context):
        """Get unread count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestUpload(self, request, context):
        """Get a presigned HTTP PUT URL to upload a file before sharing in chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadUrl(self, request, context):
        """Get a fresh presigned HTTP GET URL to download a media object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresence(self, request, context):
        """Batch presence lookup (online status + last seen)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRooms(self, request, context):
        """Get all active rooms for a user with last-message metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """Group management RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGroupMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGroupMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferOwnership(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=chat__pb2.ClientMessage.FromString,
                    response_serializer=chat__pb2.ServerMessage.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=chat__pb2.CreateRoomRequest.FromString,
                    response_serializer=chat__pb2.CreateRoomResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=chat__pb2.GetConversationRequest.FromString,
                    response_serializer=chat__pb2.GetConversationResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=chat__pb2.GetMessagesRequest.FromString,
                    response_serializer=chat__pb2.GetMessagesResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat__pb2.SendMessageRequest.FromString,
                    response_serializer=chat__pb2.SendMessageResponse.SerializeToString,
            ),
            'SearchMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMessages,
                    request_deserializer=chat__pb2.SearchMessagesRequest.FromString,
                    response_serializer=chat__pb2.SearchMessagesResponse.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=chat__pb2.DeleteMessageRequest.FromString,
                    response_serializer=chat__pb2.DeleteMessageResponse.SerializeToString,
            ),
            'EditMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.EditMessage,
                    request_deserializer=chat__pb2.EditMessageRequest.FromString,
                    response_serializer=chat__pb2.EditMessageResponse.SerializeToString,
            ),
            'MarkMessageRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkMessageRead,
                    request_deserializer=chat__pb2.MarkMessageReadRequest.FromString,
                    response_serializer=chat__pb2.MarkMessageReadResponse.SerializeToString,
            ),
            'GetUnreadCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnreadCount,
                    request_deserializer=chat__pb2.GetUnreadCountRequest.FromString,
                    response_serializer=chat__pb2.GetUnreadCountResponse.SerializeToString,
            ),
            'RequestUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUpload,
                    request_deserializer=chat__pb2.UploadRequest.FromString,
                    response_serializer=chat__pb2.UploadResponse.SerializeToString,
            ),
            'GetDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadUrl,
                    request_deserializer=chat__pb2.GetDownloadUrlRequest.FromString,
                    response_serializer=chat__pb2.GetDownloadUrlResponse.SerializeToString,
            ),
            'GetPresence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresence,
                    request_deserializer=chat__pb2.GetPresenceRequest.FromString,
                    response_serializer=chat__pb2.GetPresenceResponse.SerializeToString,
            ),
            'GetUserRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRooms,
                    request_deserializer=chat__pb2.GetUserRoomsRequest.FromString,
                    response_serializer=chat__pb2.GetUserRoomsResponse.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=chat__pb2.CreateGroupRequest.FromString,
                    response_serializer=chat__pb2.CreateGroupResponse.SerializeToString,
            ),
            'AddGroupMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGroupMember,
                    request_deserializer=chat__pb2.AddGroupMemberRequest.FromString,
                    response_serializer=chat__pb2.AddGroupMemberResponse.SerializeToString,
            ),
            'RemoveGroupMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGroupMember,
                    request_deserializer=chat__pb2.RemoveGroupMemberRequest.FromString,
                    response_serializer=chat__pb2.RemoveGroupMemberResponse.SerializeToString,
            ),
            'LeaveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGroup,
                    request_deserializer=chat__pb2.LeaveGroupRequest.FromString,
                    response_serializer=chat__pb2.LeaveGroupResponse.SerializeToString,
            ),
            'PromoteAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteAdmin,
                    request_deserializer=chat__pb2.PromoteAdminRequest.FromString,
                    response_serializer=chat__pb2.PromoteAdminResponse.SerializeToString,
            ),
            'TransferOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferOwnership,
                    request_deserializer=chat__pb2.TransferOwnershipRequest.FromString,
                    response_serializer=chat__pb2.TransferOwnershipResponse.SerializeToString,
            ),
            'DeleteGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGroup,
                    request_deserializer=chat__pb2.DeleteGroupRequest.FromString,
                    response_serializer=chat__pb2.DeleteGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chat.v1.ChatService/Chat',
            chat__pb2.ClientMessage.SerializeToString,
            chat__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/CreateRoom',
            chat__pb2.CreateRoomRequest.SerializeToString,
            chat__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetConversation',
            chat__pb2.GetConversationRequest.SerializeToString,
            chat__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetMessages',
            chat__pb2.GetMessagesRequest.SerializeToString,
            chat__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/SendMessage',
            chat__pb2.SendMessageRequest.SerializeToString,
            chat__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/SearchMessages',
            chat__pb2.SearchMessagesRequest.SerializeToString,
            chat__pb2.SearchMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/DeleteMessage',
            chat__pb2.DeleteMessageRequest.SerializeToString,
            chat__pb2.DeleteMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/EditMessage',
            chat__pb2.EditMessageRequest.SerializeToString,
            chat__pb2.EditMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkMessageRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/MarkMessageRead',
            chat__pb2.MarkMessageReadRequest.SerializeToString,
            chat__pb2.MarkMessageReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnreadCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetUnreadCount',
            chat__pb2.GetUnreadCountRequest.SerializeToString,
            chat__pb2.GetUnreadCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/RequestUpload',
            chat__pb2.UploadRequest.SerializeToString,
            chat__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetDownloadUrl',
            chat__pb2.GetDownloadUrlRequest.SerializeToString,
            chat__pb2.GetDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetPresence',
            chat__pb2.GetPresenceRequest.SerializeToString,
            chat__pb2.GetPresenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetUserRooms',
            chat__pb2.GetUserRoomsRequest.SerializeToString,
            chat__pb2.GetUserRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/CreateGroup',
            chat__pb2.CreateGroupRequest.SerializeToString,
            chat__pb2.CreateGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGroupMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/AddGroupMember',
            chat__pb2.AddGroupMemberRequest.SerializeToString,
            chat__pb2.AddGroupMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveGroupMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/RemoveGroupMember',
            chat__pb2.RemoveGroupMemberRequest.SerializeToString,
            chat__pb2.RemoveGroupMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/LeaveGroup',
            chat__pb2.LeaveGroupRequest.SerializeToString,
            chat__pb2.LeaveGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/PromoteAdmin',
            chat__pb2.PromoteAdminRequest.SerializeToString,
            chat__pb2.PromoteAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/TransferOwnership',
            chat__pb2.TransferOwnershipRequest.SerializeToString,
            chat__pb2.TransferOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/DeleteGroup',
            chat__pb2.DeleteGroupRequest.SerializeToString,
            chat__pb2.DeleteGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
